### ISSUE TITLE
Presets not applying

### ISSUE THREAD

**Issue by salinas707** [mbround18/palworld-docker#5] opened 2024-01-24 23:30 UTC
It seems like the presets (casual, normal, hard) are not applying correctly. New to python so I may be wrong, but I think there may be a typo on the config.py script here:
```python
# Check for preset and apply preset values first
    preset_values = {}
    if args.preset:
        preset_values = presets.get(args.preset, {})

    # Create a dictionary of all arguments
    args_dict = {
        key: value
        for key, value in vars(args).items()
        if key != "output" and value is not None
    }
    combined_values = {**preset_values, **args_dict}

    # Load and render the template with arguments
    # get a path of script
    script_path = os.path.dirname(os.path.realpath(__file__))
    # join a script path to templates/config.ini.j2
    template_path = os.path.join(script_path, "templates/config.ini.j2")

    template = Template(open(template_path).read())
    rendered = template.render(**args_dict)
``` 

On this line:
```python
rendered = template.render(**args_dict)  # should pass in combined_values rather than args_dict?
```

**Comment by mbround18** [comment] 2024-01-25 06:26
You are correct! I'll get the change in and test tomorrow :)

**Comment by mbround18** [comment] 2024-01-25 16:38
@salinas707 this has been fixed in the latest push of the container. I had to separate the default values from the env lookup. So the order of operations is default + preset + user set which will = full set of env vars.

**Comment by mbround18** [comment] 2024-01-25 22:45
Tested and confirmed

**Closed as completed by mbround18** 2024-01-25 22:45 UTC

**Comment by salinas707** [comment] 2024-01-26 15:42
nice work, your changes worked for me. Thank you

**Comment by cwc** [comment] 2024-02-01 04:28
The PRESET env does not appear to be working for me. I believe the problem is here: https://github.com/mbround18/palworld-docker/blob/main/scripts/config.py#L176

It looks like the `--preset` arg does not default to the PRESET env var, and I don't see anywhere else where it would be getting passed in.
